force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>FirstName__c +&apos; &apos;+ LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Session_Object__c.field-meta.xml
<CustomField>
    <fullName>Session_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Object</label>
    <referenceTo>Session_Object__c</referenceTo>
    <relationshipLabel>Loan</relationshipLabel>
    <relationshipName>Loan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Object__c/Session_Object__c.object-meta.xml
<CustomObject>
    <label>Session Object</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Session Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wire_Transfer__c/Wire_Transfer__c.object-meta.xml
<CustomObject>
    <label>Wire Transfer</label>
    <nameField>
        <displayFormat>WR-{00000}</displayFormat>
        <label>Wire Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wire Transfer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wire_Transfer__c/fields/Amount_of_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Transfer__c</fullName>
    <label>Amount of Transfer</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>FirstName__c + &apos; &apos; + LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Receiver_LastName__c.field-meta.xml
<CustomField>
    <fullName>Receiver_LastName__c</fullName>
    <label>Receiver LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Reciever_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Reciever_Account_Number__c</fullName>
    <label>Reciever Account Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Reciever_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Reciever_FirstName__c</fullName>
    <label>Reciever FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Routing_Number__c</fullName>
    <label>Routing Number</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Session_Object__c.field-meta.xml
<CustomField>
    <fullName>Session_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Object</label>
    <referenceTo>Session_Object__c</referenceTo>
    <relationshipLabel>Wire Transfer</relationshipLabel>
    <relationshipName>Wire_Transfer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MyFinance_Staus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MyFinance_Staus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>In progress</fullName>
        <default>true</default>
        <label>In progress</label>
    </customValue>
    <masterLabel>MyFinance Staus</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Repositoryes/HistoryCMPControllerRepository.cls
public with sharing class HistoryCMPControllerRepository {

	public static List<Loan__c> getLoan(String sessionId) {
		if (sessionId == null) {
			return new List<Loan__c>();
		} else {
			return [
					SELECT	
							CreatedDate,
							FirstName__c,
							Full_Name__c,
							Id,
							LastName__c,
							Name,
							Payment_Terms__c,
							Phone_Number__c,
							Status__c
					FROM Loan__c
					WHERE Session_Object__c = :sessionId
					];
		}
	}

	public static List<Wire_Transfer__c> getWire(String sessionId) {
		if (sessionId == null) {
			return new List<Wire_Transfer__c>();
		} else {
			return [
					SELECT  
							Account_Number__c,
							Amount_of_Transfer__c,
							Bank_Name__c,
							CreatedDate,
							Date__c,
							FirstName__c,
							Full_Name__c,
							Id,
							LastName__c,
							Name,
							Receiver_LastName__c,
							Reciever_Account_Number__c,
							Reciever_FirstName__c,
							Routing_Number__c,
							Status__c
					FROM Wire_Transfer__c
					WHERE Session_Object__c = :sessionId
					];
		}
	}
}