force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Desire_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Desire_Loan_Amount__c</fullName>
    <label>Desire Loan Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Session_Object__c.field-meta.xml
<CustomField>
    <fullName>Session_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Object</label>
    <referenceTo>Session_Object__c</referenceTo>
    <relationshipLabel>Loan</relationshipLabel>
    <relationshipName>Loan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RESTSetting__mdt/RESTSetting__mdt.object-meta.xml
<CustomObject>
    <label>RESTSetting</label>
    <pluralLabel>RESTSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/RESTSetting__mdt/fields/grant_type__c.field-meta.xml
<CustomField>
    <fullName>grant_type__c</fullName>
    <label>grant_type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RESTSetting__mdt/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <label>password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RESTSetting__mdt/fields/setEndpoint__c.field-meta.xml
<CustomField>
    <fullName>setEndpoint__c</fullName>
    <label>setEndpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RESTSetting__mdt/fields/setHeaderApp__c.field-meta.xml
<CustomField>
    <fullName>setHeaderApp__c</fullName>
    <label>setHeaderApp</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RESTSetting__mdt/fields/setHeaderType__c.field-meta.xml
<CustomField>
    <fullName>setHeaderType__c</fullName>
    <label>setHeaderType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RESTSetting__mdt/fields/setMethod__c.field-meta.xml
<CustomField>
    <fullName>setMethod__c</fullName>
    <label>setMethod</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Object__c/Session_Object__c.object-meta.xml
<CustomObject>
    <label>Session Object</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Session Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wire_Transfer__c/Wire_Transfer__c.object-meta.xml
<CustomObject>
    <label>Wire Transfer</label>
    <nameField>
        <displayFormat>WR-{00000}</displayFormat>
        <label>Wire Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wire Transfer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wire_Transfer__c/fields/Amount_of_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Transfer__c</fullName>
    <label>Amount of Transfer</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Receiver_LastName__c.field-meta.xml
<CustomField>
    <fullName>Receiver_LastName__c</fullName>
    <label>Receiver LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Reciever_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Reciever_Account_Number__c</fullName>
    <label>Reciever Account Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Reciever_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Reciever_FirstName__c</fullName>
    <label>Reciever FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Routing_Number__c</fullName>
    <label>Routing Number</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Session_Object__c.field-meta.xml
<CustomField>
    <fullName>Session_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Object</label>
    <referenceTo>Session_Object__c</referenceTo>
    <relationshipLabel>Wire Transfer</relationshipLabel>
    <relationshipName>Wire_Transfer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Controllers/EmbeddedSigningController.cls
public without sharing class EmbeddedSigningController {
	@AuraEnabled
	public static String sendEnvelope(String template, String description, Id recordId) {
		String sObjectName = recordId.getSObjectType().getDescribe().getName();
		if(sObjectName == 'Loan__c'){
			return getloanEnvelope(template,description,recordId);
		}else if(sObjectName == 'Wire_Transfer__c'){
			return getwireTransferEnvelope(template,description,recordId);
		}
		return '';
	}

	private static String getloanEnvelope(String template, String description, Id recordId){
		Loan__c l = [SELECT 
						FirstName__c,
						LastName__c,
						Email__c,
						Phone_Number__c,
						Desire_Loan_Amount__c,
						Currency__c,
						Payment_Terms__c 
						FROM Loan__c 
						WHERE Id =: recordId];
		dfsle.Envelope dsEnvelope = dfsle.EnvelopeService.getEmptyEnvelope(
			new dfsle.Entity(recordId))
			.withDocuments(new List<dfsle.Document>{
					dfsle.Document.fromTemplate(dfsle.UUID.parse(template), description)
			})
			.withRecipients(new List<dfsle.Recipient>{
				dfsle.Recipient.newEmbeddedSigner().withTabs(new List<dfsle.Tab>{
					generateTab(l.FirstName__c, 200,210),
					generateTab(l.LastName__c, 200 ,235),
					generateTab(l.Email__c, 200,265),
					generateTab(l.Phone_Number__c, 200,295),
					generateTab(String.Valueof(l.Desire_Loan_Amount__c), 200,380),
					generateTab(String.ValueOf(l.Payment_Terms__c.format()), 200,405),
					createSignTab(200,430)
				})
			});
		dsEnvelope = dfsle.EnvelopeService.sendEnvelope(
				dsEnvelope,
				true
		);
		return String.valueOf(dsEnvelope.docuSignId);
	}

	private static String getWireTransferEnvelope(String template, String description, Id recordId){
		Wire_Transfer__c w = [SELECT 
								FirstName__c,
								LastName__c,
								Account_Number__c,
								Amount_of_Transfer__c,
								Date__c,
								Reciever_FirstName__c,
								Receiver_LastName__c,
								Bank_Name__c,
								Reciever_Account_Number__c,
								Routing_Number__c 
								FROM Wire_Transfer__c 
								WHERE Id =: recordId];
		dfsle.Envelope dsEnvelope = dfsle.EnvelopeService.getEmptyEnvelope(
			new dfsle.Entity(recordId))
			.withDocuments(new List<dfsle.Document>{
					dfsle.Document.fromTemplate(dfsle.UUID.parse(template), description)
			})
			.withRecipients(new List<dfsle.Recipient>{
				dfsle.Recipient.newEmbeddedSigner().withTabs(new List<dfsle.Tab>{
					generateTab(w.FirstName__c, 200,230),
					generateTab(w.LastName__c, 200 ,255),
					generateTab(w.Account_Number__c, 200,280),
					generateTab(String.Valueof(w.Amount_of_Transfer__c), 200,310),
					generateTab(String.ValueOf(w.Date__c.format()), 200,345),
					generateTab(w.Reciever_FirstName__c, 200 ,445),
					generateTab(w.Receiver_LastName__c, 200 ,475),
					generateTab(w.Bank_Name__c, 200 ,505),
					generateTab(String.ValueOf(w.Reciever_Account_Number__c), 200 ,530),
					generateTab(String.ValueOf(w.Routing_Number__c), 200 ,555),
					createSignTab(200, 550)
				})
			});
		dsEnvelope = dfsle.EnvelopeService.sendEnvelope(
				dsEnvelope,
				true
		);
		return String.valueOf(dsEnvelope.docuSignId);
	}

	private static dfsle.Tab generateTab(final String value, final Integer X_position, final Integer Y_position) {
		dfsle.Tab myTextTab = new dfsle.TextTab()
				.withValue(value)
				.withPosition(new dfsle.Tab.Position(
						1,
						1,
						X_position,
						Y_position,
						100,
						null));
		return myTextTab;
	}

	private static dfsle.Tab createSignTab(final Integer X_position, final Integer Y_position){
		dfsle.Tab mySignHereTab = new dfsle.SignHereTab()
			.withScale(0.5) 
			.withRequired(true) 
			.withAnchor(new dfsle.Tab.Anchor(
			'signature', 
			false, 
			false, 
			'right', 
			true, 
			true, 
			'pixels', 
			X_position, 
			Y_position));
			return mySignHereTab;
	}

	@AuraEnabled
	public static String getEmbedSigningUrl(String envId, String url) {
		Url embeddedSigningUrl = dfsle.SigningService.getEmbeddedSigningUrl(
			dfsle.UUID.parse(envId), new URL(url)
		);
		return String.valueOf(embeddedSigningUrl.toExternalForm());
	}

	@AuraEnabled
	public static Id createSession() {
		addDocuSignPermissionSetIfNotExists(UserInfo.getUserId());
		Session_Object__c sess = new Session_Object__c();
		insert sess;
		return sess.Id;
	}

	public static void addDocuSignPermissionSetIfNotExists(Id userId) {
		if (userId != null) {
			List<PermissionSetAssignment> pSets = [
					SELECT 
						Id, 
						PermissionSetId,
						PermissionSet.Name,
						PermissionSet.ProfileId,
						PermissionSet.Profile.Name,
						AssigneeId,
						Assignee.Name
					FROM PermissionSetAssignment
					WHERE
					PermissionSet.Name LIKE '%Sender%'
					AND AssigneeId = :userId
			];
			if (pSets.isEmpty()) {
				HttpResponse authorizationResponse = authorize();
				if (authorizationResponse.getStatusCode() == 200) {
					createAssigmentRestCallout(authorizationResponse.getBody(),userId);
				}
			}
		}
	}

	public static HttpResponse authorize() {
		RESTSetting__mdt authorizationEndpointSettings = [
				SELECT 
						DeveloperName,
						setEndpoint__c,
						setMethod__c,
						setHeaderType__c,
						setHeaderApp__c,
						grant_type__c,
						client_id__c,
						client_secret__c,
						username__c,
						password__c
				FROM RESTSetting__mdt
				WHERE DeveloperName = 'DocuSignAuthorizationEndpointSettings'
				LIMIT 1
		];
	
		HttpResponse authorizationResponse = sendAuthorizationRequest(authorizationEndpointSettings);
		return authorizationResponse;
	}

	public static HttpResponse sendAuthorizationRequest(RESTSetting__mdt authorizationEndpointSettings) {
		HttpRequest request = new HttpRequest();
		request.setEndpoint(authorizationEndpointSettings.setEndpoint__c);
		request.setMethod(authorizationEndpointSettings.setMethod__c);
		request.setHeader(authorizationEndpointSettings.setHeaderType__c, authorizationEndpointSettings.setHeaderApp__c);
		request.setBody(getBodyForAuthorizationRequest(authorizationEndpointSettings));
		HttpResponse authorizationResponse = new Http().send(request);
		return authorizationResponse;
	}
	
	private static String getBodyForAuthorizationRequest(RESTSetting__mdt authorizationEndpointSettings) {
		return 'grant_type=' + authorizationEndpointSettings.grant_type__c +
				+'&client_id=' + authorizationEndpointSettings.client_id__c +
				+'&client_secret=' + authorizationEndpointSettings.client_secret__c +
				+'&username=' + authorizationEndpointSettings.username__c +
				+'&password=' + authorizationEndpointSettings.password__c;
	}
	
	public static void createAssigmentRestCallout(String body, String userId) {
		Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(body);
		String token = (String) results.get('access_token');
		String instanceURL = (String) results.get('instance_url');
		HttpRequest request = new HttpRequest();
		String bodyRequest = '{"userId":"' + userId + '"}';
		request.setEndpoint(instanceURL + '/services/apexrest/createAssigment');
		request.setMethod('POST');
		request.setBody(bodyRequest);
		request.setHeader('Authorization', 'Bearer ' + token);
		request.setHeader('Content-Type', 'application/json');
		new Http().send(request);
	}
}