force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Session_Object__c.field-meta.xml
<CustomField>
    <fullName>Session_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Object</label>
    <referenceTo>Session_Object__c</referenceTo>
    <relationshipLabel>Loan</relationshipLabel>
    <relationshipName>Loan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Object__c/Session_Object__c.object-meta.xml
<CustomObject>
    <label>Session Object</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Session Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Object</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wire_Transfer__c/Wire_Transfer__c.object-meta.xml
<CustomObject>
    <label>Wire Transfer</label>
    <nameField>
        <displayFormat>WR-{00000}</displayFormat>
        <label>Wire Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wire Transfer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wire_Transfer__c/fields/Session_Object__c.field-meta.xml
<CustomField>
    <fullName>Session_Object__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Object</label>
    <referenceTo>Session_Object__c</referenceTo>
    <relationshipLabel>Wire Transfer</relationshipLabel>
    <relationshipName>Wire_Transfer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Tests/HistoryCMPControllerTest.cls
@IsTest
private class HistoryCMPControllerTest {

	@TestSetup static void testSetup() {
		Session_Object__c session = new Session_Object__c();
		insert session;
		insert new Loan__c(Session_Object__c = session.Id);
		insert new Wire_Transfer__c(Session_Object__c = session.Id);
	}


	@IsTest
	public static void getHistoryRecords_ExecutesSuccessfully() {
		Session_Object__c session = [SELECT Id FROM Session_Object__c];
		String historyRecordsString = HistoryCMPController.getHistoryRecords(String.valueOf(session.Id));
		List<HistoryRecordWrapper> historyRecords = (List<HistoryRecordWrapper>) JSON.deserialize(historyRecordsString, List<HistoryRecordWrapper>.class);
		System.assertNotEquals(null, historyRecords);
		System.assertEquals(2, historyRecords.size());
		
		for (HistoryRecordWrapper wr: historyRecords) {
			System.assertNotEquals(null, wr.status);
			System.assertEquals(null, wr.applicant);
		}
	}
}