force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{000000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>FirstName__c +&apos; &apos;+ LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/Wire_Transfer__c.object-meta.xml
<CustomObject>
    <label>Wire Transfer</label>
    <nameField>
        <displayFormat>WR-{00000}</displayFormat>
        <label>Wire Transfer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wire Transfer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wire_Transfer__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>FirstName__c + &apos; &apos; + LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wire_Transfer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MyFinance_Staus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MyFinance_Staus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>In progress</fullName>
        <default>true</default>
        <label>In progress</label>
    </customValue>
    <masterLabel>MyFinance Staus</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Providers/HistoryCMPControllerProvider.cls
public with sharing class HistoryCMPControllerProvider {

	public List<HistoryRecordWrapper> getHistoryRecordsWrapperList(String sessionId) {
		List<SObject> sObjectList = new List<SObject>();
		sObjectList.addAll(HistoryCMPControllerRepository.getLoan(sessionId));
		sObjectList.addAll(HistoryCMPControllerRepository.getWire(sessionId));
		List<HistoryRecordWrapper> historyRecordWrappers = new List<HistoryRecordWrapper>();
		for (SObject record : sObjectList) {
			String typeOfRecord = String.valueOf(record.getSObjectType());
			HistoryRecordWrapper wrapper = new HistoryRecordWrapper();
			String userName = String.valueOf(record?.get('Full_Name__c'));
			wrapper.applicant = userName;
			wrapper.lastUpdated = Datetime.valueOf(record.get('CreatedDate')).format('MMMMM dd, yyyy hh:mm:ss a');
			final String statusValue = String.valueOf(record?.get('Status__c'));
			wrapper.status = String.isNotBlank(statusValue) ? statusValue : '-';

			if (typeOfRecord.equals('Loan__c')) {
				wrapper.subject = HistoryRecordWrapper.LOAN_APPLICATION;
			}

			if (typeOfRecord.equals('Wire_Transfer__c')) {
				wrapper.subject = HistoryRecordWrapper.TRANSFER_APPLICATION;
			}
			historyRecordWrappers.add(wrapper);
		}
		return historyRecordWrappers;
	}
}